name: Run Auto-Tests
on:
  push:
    paths:
      - 'hina/**'
      - '.github/workflows/auto-test.yml'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          pip install networkx
          pip install hina
      - name: Run Auto-Tests
        run: pytest Tests/
