name: Run Auto-Tests

on:
  push:
    paths:
      - 'hina/**'
      - '.github/workflows/auto-test.yml'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest networkx hina

      - name: Run HINA Tests
        run: |
          pytest hina/ --maxfail=3 --disable-warnings --tb=short

      - name: Upload Test Results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: .pytest_cache/
